name: Get Latest Workflow Runs as Output

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        description: 'Workflow file name'
        required: true
      output_file:
        description: 'Output file name'
        required: true
        default: 'output.csv'
        type: string

jobs:
  get_latest_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch organization name
        id: fetch_org_name
        run: |
          org_name=$(echo "${{ github.event.repository.owner.login }}")
          if [ -z "$org_name" ]; then
            echo "Organization name not found."
            exit 1
          fi
          echo "::set-output name=org_name::$org_name"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python script
        if: steps.fetch_org_name.outputs.org_name != ''
        id: run_python_script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python get-latest-workflow-runs.py -o "${{ steps.fetch_org_name.outputs.org_name }}" -w "${{ github.event.inputs.workflow_file }}" -f "${{ github.event.inputs.output_file }}"

      - name: Check organization name
        if: steps.fetch_org_name.outputs.org_name == ''
        run: echo "Error: Organization name not found."

      - name: Upload CSV artifact
        if: success() && steps.fetch_org_name.outputs.org_name != ''
        uses: actions/upload-artifact@v2
        with:
          name: output-csv
          path: ${{ github.event.inputs.output_file }}
